### ISSUE TITLE
question about Deep Grasp: input

### ISSUE THREAD

**Issue by ZHOUXINWEN** [ivalab/grasp_multiObject#1]
I have read the paper Deep Grasp: Detection and Localization of Grasps with Deep Neural Network.
In that paper, the RGB-D image is used as input. But the pretrained network is usually pretrained in 3 channels image (RGB). I wonder if the RGB-D mentioned in the paper is accutually RGD?

**Comment by pv33** [comment]
Yes, we use RGD.  Details on the input pre-processing can be found in Section V.A.

**Comment by ZHOUXINWEN** [comment]
Thank you!
