### ISSUE TITLE
WHen will all code  be publicly released?😀

### ISSUE THREAD

**Issue by ClaireTun** [ivalab/grasp_multiObject#2]

**Comment by fujenchu** [comment]
Thank you for your interests. We plan to release all the code upon acceptance. If you have any question, please feel free to contact the corresponding author (fujenchu@gatech.edu). We are happy to help if you want to train a grasp detector or reproduce the results.

**Comment by ClaireTun** [comment]
Wow,ok! Thank you ! Lookig forward to it !
