### ISSUE TITLE
normalize the depth information to 0-255

### ISSUE THREAD

**Issue by jinhuan-hit** [ivalab/grasp_multiObject#5]
Hi，recently I am reading your paper and trying to reproduce the results.The code in rgbd2rgd.m as below：
% re-ragne to 0~225
    depth = (double(depth)-500)/(1200-500)*255;
    depthImgUint = uint8(depth);
I confuse about the value of 500 and 1200.Are they the nearest distance or the furthest distance from the object to the camera？
Another problem is that  “The mean image is chosen to be 144, while the pixels on the depth image with no information were replaced with zeros” in Section V.A.I do not know why the mean image is chosen to be 144,not 128.And why the missed depth information are replaced with 0,not the average value of their's surrdounings?

**Comment by fujenchu** [comment]
Hi @jinhuan-hit 

Yes, you are correct. They are nearest and furthest distances, respectively.
The reason we selected 144 instead of 128 (and zeros for replacement) was due to Redmon et al. used the same value. For fair comparison, we tried to keep the same variables.

**Comment by jinhuan-hit** [comment]
@fujenchu Thanks for your reply.It helps me a lot.
